# GENERATED by spikes/spine-adopt/src/lower.mts — do not hand-edit.
#
# Record:    d-requires-file.rule.yaml (specimen d-file)
# Rule id:   0123456789abcdef
# Engine:    regex
# Contract:  spikes/spine-adopt/rego/LOWERING.md
#
# § Lowering 8 — severity/message are compile-time constants, emitted for the
# report and deliberately NOT part of the verdict comparison.

package totem.spike.r0123456789abcdef_d_file

rule_id := "0123456789abcdef"

severity := "warning"

# ─── § Lowering 5 — scope: the § Design 7 two-array rule ───────────────────
#
# Globs were lowered to ANCHORED regexes on the TS side; the path is
# separator-normalised here exactly as `matchGlob` does (sys/glob.ts:354),
# and matching is case-SENSITIVE (no `i` anywhere in the shipped profile).

normalized_file := replace(input.file, "\\", "/")

positive_globs := [
	"^(?:[^/]+/)*[^/]*\\.sh$",
	"^(?:[^/]+/)*[^/]*\\.cjs$",
]

exclude_globs := []

positive_match if {
	some g in positive_globs
	regex.match(g, normalized_file)
}

exclude_match if {
	some g in exclude_globs
	regex.match(g, normalized_file)
}

# An EMPTY positives list matches NOTHING (the record profile's direction,
# the opposite of legacy `fileMatchesGlobs`) — `positive_match` simply has
# no binding to succeed on.
in_scope if {
	positive_match
	not exclude_match
}

# ─── § Lowering 2 — strictness, made structural ────────────────────────────
#
# MEASURED, not assumed: an OPA WASM module has no `--strict-builtin-errors`
# equivalent. A `regex.match` compile failure inside a PARTIAL rule body
# simply yields no member, so an inexpressible pattern would degrade to an
# empty `violations` set — the fail-open § Lowering 2 calls
# spike-invalidating. Every emitted pattern is therefore exercised in the
# COMPLETE rule's body below: a compile failure makes `result` UNDEFINED, the
# entrypoint returns an empty result SET, and the host raises an error row.
# `is_boolean` is what keeps a legitimate non-match from failing the probe.
patterns_compile if {
	is_boolean(regex.match("^(?:[^/]+/)*[^/]*\\.sh$", ""))
	is_boolean(regex.match("^(?:[^/]+/)*[^/]*\\.cjs$", ""))
	is_boolean(regex.match("\\bgit\\s+(log|diff|status)\\b", ""))
	is_boolean(regex.match("LC_ALL=C", ""))
}

# The FactBundle's own shape, asserted rather than assumed: a malformed bundle
# must be an error row too, never a silent zero-violation verdict.
facts_wellformed if {
	is_string(input.file)
	is_array(input.lines)
	is_array(input.astMatches)
	count([1 | some l in input.lines; is_string(l)]) == count(input.lines)
	count([1 | some m in input.astMatches; ast_match_wellformed(m)]) == count(input.astMatches)
}

ast_match_wellformed(m) if {
	is_number(m.lineNumber)
	is_string(m.lineText)
	is_string(m.startLineText)
}

# ─── § Lowering 7 — suppression ────────────────────────────────────────────

same_line_markers := [
	"totem-ignore",
	"totem-context:",
	"shield-context:",
]

preceding_line_markers := [
	"totem-ignore-next-line",
	"totem-context:",
]

# The regex arm anchors on the matched line and its preceding line.
suppressed(i) if {
	some m in same_line_markers
	contains(input.lines[i], m)
}

suppressed(i) if {
	i > 0
	some m in preceding_line_markers
	contains(input.lines[i - 1], m)
}

# ─── § Lowering 6 — the `requires:` two-pass ───────────────────────────────
#
# TRUE means the required context is PRESENT, i.e. the rule stays SILENT:
# no violation AND no event of any kind (silence, never suppression).
# scope: file
#
# `fileText == null` ⇒ requirement UNMET ⇒ FIRE. Written as an explicit
# guard, never as a default: an absent/unreadable file must fail TOWARD
# flagging. `''` is a readable empty file and matches only ''-matching
# requirements — the M3 split, preserved because the guard tests `null`
# rather than truthiness.
requirement_met(_) if {
	input.fileText != null
	regex.match("LC_ALL=C", input.fileText)
}

# ─── § Lowering 1 — the output contract ────────────────────────────────────

# § Lowering 1: regex ordinal is ALWAYS 0 — the shipped regex path emits at
# most one violation per added line (worker.ts:53-62).
target_hit(i) if {
	regex.match("\\bgit\\s+(log|diff|status)\\b", input.lines[i])
}

violations contains v if {
	in_scope
	some i, _ in input.lines
	target_hit(i)
	not suppressed(i)
	not requirement_met(i)
	v := {"rule_id": rule_id, "line_number": i + 1, "ordinal": 0}
}

events contains e if {
	in_scope
	some i, _ in input.lines
	target_hit(i)
	not suppressed(i)
	not requirement_met(i)
	e := {"kind": "trigger", "line_number": i + 1, "ordinal": 0}
}

# (N2) REQUIRES IS CHECKED FIRST, then suppression — the shipped order on all
# three dispatchers (rule-engine.ts:689 before :701; apply-rules-bounded.ts:207
# before :233). A requires-SATISFIED match is therefore silent even when the
# line also carries a suppression marker: no violation and no event of any
# kind. LOWERING.md does not order the two, so the shipped order is followed.
events contains e if {
	in_scope
	some i, _ in input.lines
	target_hit(i)
	not requirement_met(i)
	suppressed(i)
	e := {"kind": "suppress", "line_number": i + 1, "ordinal": 0}
}

# The entrypoint. A COMPLETE rule guarded on the two structural probes, so
# any builtin error or malformed bundle leaves it UNDEFINED and the host sees
# an empty result SET — which it must raise as an error, never read as a
# zero-violation verdict (§ Lowering 2, and the Host contract's strictness).
result := {"violations": violations, "events": events} if {
	patterns_compile
	facts_wellformed
}
