import { z } from 'zod';

// ─── NapiConfig / compound ast-grep rule schemas ────

/**
 * Schema mirroring `@ast-grep/napi`'s `NapiConfig` interface for compound
 * structural rules. The `rule` key is required at the Zod layer so the
 * parse-time failure is loud and readable; the inner tree shape is handed
 * off to `@ast-grep/napi` at the engine boundary for the authoritative
 * validity check (see `validateAstGrepPattern`). `passthrough()` lets
 * future napi fields (e.g. `constraints`, `transform`) survive a parse
 * without a schema bump.
 *
 * The rule body is a recursive structural tree (combinators like `all`,
 * `any`, `not`, `inside`, `has`, `precedes`, `follows`). Rather than
 * modelling the full recursive schema with `z.lazy()`, we accept any
 * object shape here and lean on napi to reject malformed trees. That
 * keeps the Zod layer cheap and the authoritative check centralized.
 */
export const NapiConfigSchema = z
  .object({
    rule: z.record(z.unknown()),
  })
  .passthrough();

export type NapiConfig = z.infer<typeof NapiConfigSchema>;

/**
 * Named alias of `NapiConfigSchema` for grep-ability. The field on
 * `CompiledRule` is named `astGrepYamlRule` (see ADR-087); the alias
 * lets a reader search for `AstGrepYamlRuleSchema` and land on the
 * right definition without first knowing it's a napi config.
 */
export const AstGrepYamlRuleSchema = NapiConfigSchema;

export type AstGrepYamlRule = NapiConfig;

// ─── Compiled rule schemas ──────────────────────────

const CompiledRuleBaseSchema = z.object({
  /** SHA-256 hash (first 16 hex chars) of heading + body — detects edits */
  lessonHash: z.string(),
  /** Human-readable heading from the lesson (for diagnostics) */
  lessonHeading: z.string(),
  /** Regex pattern to match against added diff lines */
  pattern: z.string(),
  /** Human-readable violation message shown when the pattern matches */
  message: z.string(),
  /** Engine type — 'regex' for line-level matching, 'ast' for Tree-sitter S-expression queries, 'ast-grep' for ast-grep structural patterns */
  engine: z.enum(['regex', 'ast', 'ast-grep']),
  /** Tree-sitter S-expression query (required when engine is 'ast') */
  astQuery: z.string().optional(),
  /**
   * Flat ast-grep pattern source (a single JS/TS expression). Mutually
   * exclusive with `astGrepYamlRule` when `engine === 'ast-grep'`; the
   * superRefine below enforces that.
   */
  astGrepPattern: z.string().optional(),
  /**
   * Compound ast-grep rule (NapiConfig shape). Holds structural trees
   * that cannot be expressed as a single source snippet (all / any /
   * not / inside / has / precedes / follows combinators). Mutually
   * exclusive with `astGrepPattern`; see the superRefine on this
   * schema. Smoke-test wiring lands in mmnto/totem#1408.
   */
  astGrepYamlRule: AstGrepYamlRuleSchema.optional(),
  /**
   * Optional code snippet the rule is expected to match. Stored from
   * compiler output so the smoke-test runner (wired in
   * mmnto/totem#1408) can re-validate the rule offline. Optional in
   * 1.14.9; flips to required when #1408 turns on the gate.
   */
  badExample: z.string().optional(),
  /** ISO timestamp of when this rule was compiled */
  compiledAt: z.string(),
  /** ISO timestamp of when this rule was first created (survives recompilation) */
  createdAt: z.string().optional(),
  /** Optional file glob patterns — rule only applies to matching files (e.g., ["*.sh", "*.yml"]) */
  fileGlobs: z.array(z.string()).optional(),
  /** Rule category for Trap Ledger classification */
  category: z.enum(['security', 'architecture', 'style', 'performance']).optional(),
  /** Severity level — error blocks CI, warning reports but doesn't fail */
  severity: z.enum(['error', 'warning']).optional(),
  /** Lifecycle status — active rules are enforced, archived rules are skipped */
  status: z.enum(['active', 'archived']).optional(),
  /** Reason for archiving (when status is 'archived') */
  archivedReason: z.string().optional(),
  /**
   * True for rules generated by Pipeline 1 (manual `**Pattern:**` blocks). Set to
   * `true` in `buildManualRule`. Used by `doctor.ts:checkUpgradeCandidates` and
   * `compile.ts:logCompiledRule` to identify manual rules without relying on the
   * fragile `lessonHeading === message` heuristic — that heuristic only worked
   * pre-#1265 when manual rules had no way to express a custom message and the
   * compiler hardcoded `message: lesson.heading`. After #1265 added Pipeline 1
   * Message field support, manual rules can now have rich messages distinct from
   * their headings, breaking the heuristic. The `manual` flag is the reliable
   * post-#1265 signal. Optional + missing for backward compat with pre-#1265
   * compiled-rules.json files; the legacy heuristic stays as a fallback.
   */
  manual: z.boolean().optional(),
});

/**
 * Shared mutual-exclusion check between the flat `astGrepPattern` string
 * and the structural `astGrepYamlRule` object. Used by both
 * `CompiledRuleSchema` and `CompilerOutputSchema` so the gate fires at
 * both the LLM-output boundary and the persisted-rule boundary. Empty
 * strings count as "not present" because `engineFields` writes
 * `pattern: ''` alongside every ast-grep rule.
 */
function refineAstGrepMutualExclusion(
  data: {
    engine?: 'regex' | 'ast' | 'ast-grep';
    astGrepPattern?: string;
    astGrepYamlRule?: unknown;
  },
  ctx: z.RefinementCtx,
): void {
  if (data.engine !== 'ast-grep') return;
  const hasPattern = typeof data.astGrepPattern === 'string' && data.astGrepPattern.length > 0;
  const hasYaml = data.astGrepYamlRule !== undefined;
  if (hasPattern && hasYaml) {
    ctx.addIssue({
      code: z.ZodIssueCode.custom,
      message: 'ast-grep rule cannot define both astGrepPattern and astGrepYamlRule',
      path: ['astGrepYamlRule'],
    });
  }
  if (!hasPattern && !hasYaml) {
    ctx.addIssue({
      code: z.ZodIssueCode.custom,
      message: 'ast-grep rule must define either astGrepPattern or astGrepYamlRule',
      path: ['astGrepPattern'],
    });
  }
}

export const CompiledRuleSchema = CompiledRuleBaseSchema.superRefine(refineAstGrepMutualExclusion);

export type CompiledRule = z.infer<typeof CompiledRuleSchema>;

/**
 * A non-compilable lesson entry. Pre-#1280 these were opaque hash strings;
 * post-#1280 they're {hash, title} tuples for human-readable triage. The
 * loader normalizes legacy strings to tuples on read so downstream code only
 * ever sees the tuple form.
 */
export const NonCompilableEntrySchema = z
  .union([
    z.string(),
    z.object({
      hash: z.string(),
      title: z.string(),
    }),
  ])
  .transform((entry) =>
    typeof entry === 'string' ? { hash: entry, title: '(legacy entry)' } : entry,
  );

export type NonCompilableEntry = z.infer<typeof NonCompilableEntrySchema>;

export const CompiledRulesFileSchema = z.object({
  version: z.literal(1),
  rules: z.array(CompiledRuleSchema),
  /**
   * Lesson hashes that the LLM determined cannot be compiled (conceptual/architectural).
   * Stored as `{hash, title}` tuples for observability (#1280). Legacy `string[]` form
   * is accepted on read and normalized to tuples by `NonCompilableEntrySchema.transform`.
   */
  nonCompilable: z.array(NonCompilableEntrySchema).optional(),
});

export type CompiledRulesFile = z.infer<typeof CompiledRulesFileSchema>;

// ─── Compiler output schema ─────────────────────────

/** Schema for the structured JSON the LLM returns when compiling a lesson. */
const CompilerOutputBaseSchema = z.object({
  compilable: z.boolean(),
  pattern: z.string().optional(),
  message: z.string().optional(),
  fileGlobs: z.array(z.string()).optional(),
  engine: z.enum(['regex', 'ast', 'ast-grep']).optional(),
  astQuery: z.string().optional(),
  /** Flat ast-grep pattern source. Mutually exclusive with `astGrepYamlRule`. */
  astGrepPattern: z.string().optional(),
  /** Compound ast-grep rule (NapiConfig). Mutually exclusive with `astGrepPattern`. */
  astGrepYamlRule: AstGrepYamlRuleSchema.optional(),
  /**
   * Optional code snippet the rule is expected to match. Optional in
   * 1.14.9; gate wired in mmnto/totem#1408.
   */
  badExample: z.string().optional(),
  severity: z.enum(['error', 'warning']).optional(),
  /** LLM explanation for why a lesson was marked non-compilable */
  reason: z.string().optional(),
});

export const CompilerOutputSchema = CompilerOutputBaseSchema.superRefine(
  refineAstGrepMutualExclusion,
);

export type CompilerOutput = z.infer<typeof CompilerOutputSchema>;

// ─── Violation type ─────────────────────────────────

export interface Violation {
  /** The rule that was violated */
  rule: CompiledRule;
  /** The file path from the diff where the violation occurred */
  file: string;
  /** The matching line content */
  line: string;
  /** 1-based line number within the diff hunk (approximate) */
  lineNumber: number;
}

// ─── Diff types ─────────────────────────────────────

/** Syntactic context of a diff line, determined by AST analysis. */
export type AstContext = 'code' | 'string' | 'comment' | 'regex';

export interface DiffAddition {
  file: string;
  line: string;
  lineNumber: number;
  /** Content of the preceding line in the new file (context or added), null if first in hunk */
  precedingLine: string | null;
  /** Syntactic context from AST analysis — undefined means not classified (fail-open as code) */
  astContext?: AstContext;
}

// ─── Shared types ───────────────────────────────────

export interface RegexValidation {
  valid: boolean;
  reason?: string;
}

/** Context passed alongside rule events for Trap Ledger integration. */
export interface RuleEventContext {
  file: string;
  line: number;
  justification?: string;
  /** AST context where the rule fired (code, string, comment, regex). */
  astContext?: AstContext;
  /**
   * Populated on `'failure'` events only. Holds the error message surfaced by
   * the runtime engine (ast-grep `findAll`, regex `exec`, etc.) so `totem
   * doctor` telemetry can aggregate rules that fail at execution time. Not
   * used by `'trigger'` or `'suppress'` events. Kept as a string rather than
   * the raw `unknown` so the callback interface stays cheap to consume.
   */
  failureReason?: string;
}

/**
 * Callback for observability - invoked when a rule is suppressed, triggered,
 * or fails at runtime. The `'failure'` variant was added in mmnto/totem#1408
 * alongside per-rule try/catch in `executeQuery`. It is intentionally distinct
 * from `'suppress'`: suppression is a user-initiated directive (totem-ignore /
 * totem-context), while failure is a runtime engine error on a rule that
 * otherwise compiled. The #1412 postmerge GCA fix established this boundary,
 * so the two values must NEVER be conflated in the Trap Ledger.
 */
export type RuleEventCallback = (
  event: 'trigger' | 'suppress' | 'failure',
  lessonHash: string,
  context?: RuleEventContext,
) => void;
