import * as fs from 'node:fs';
import * as path from 'node:path';

import type { ParsedLesson } from './drift-detector.js';
import { TotemParseError } from './errors.js';

// ─── Constants ─────────────────────────────────────────

export const SENTINEL_START = '<!-- totem:generated:start -->';
export const SENTINEL_END = '<!-- totem:generated:end -->';

// ─── Markdown formatting ─────────────────────────────

/**
 * Format parsed lessons as a markdown block for injection into AI config files.
 * Always generates sentinel markers (even for empty lessons) to preserve idempotency.
 */
export function formatLessonsAsMarkdown(lessons: ParsedLesson[]): string {
  const lines: string[] = [
    SENTINEL_START,
    '<!-- Auto-generated by `totem compile --export`. Do not edit between these markers. -->',
    '',
    '## Totem Project Rules',
    '',
  ];

  for (const lesson of lessons) {
    const bodyOneLine = lesson.body.replace(/\n+/g, ' ').trim();
    const tags = lesson.tags.length > 0 ? ` *(${lesson.tags.join(', ')})*` : '';
    lines.push(`- **${lesson.heading}** — ${bodyOneLine}${tags}`);
  }

  lines.push('', SENTINEL_END);
  return lines.join('\n');
}

// ─── Sentinel injection ──────────────────────────────

/**
 * Inject a generated block between sentinel markers in file content.
 * - If sentinels exist: replaces content between them (inclusive)
 * - If no sentinels: appends block to end of file
 * - If mismatched sentinels (start without end): throws error
 */
export function injectSentinelBlock(existingContent: string, generatedBlock: string): string {
  const startIdx = existingContent.indexOf(SENTINEL_START);
  const endIdx = existingContent.indexOf(SENTINEL_END);

  if (startIdx !== -1 && endIdx === -1) {
    throw new TotemParseError(
      `Found ${SENTINEL_START} without matching ${SENTINEL_END}.`,
      'Fix the target file manually — ensure both sentinel markers are present and correctly ordered.',
    );
  }

  if (startIdx !== -1 && endIdx !== -1 && endIdx < startIdx) {
    throw new TotemParseError(
      `Found ${SENTINEL_END} before ${SENTINEL_START}.`,
      'Fix the target file manually — ensure sentinel markers appear in the correct order.',
    );
  }

  if (startIdx !== -1 && endIdx !== -1) {
    const before = existingContent.slice(0, startIdx);
    const after = existingContent.slice(endIdx + SENTINEL_END.length);
    return before + generatedBlock + after;
  }

  // No sentinels — append to end (no-op if nothing to inject)
  if (generatedBlock === '') return existingContent;
  if (existingContent.trim() === '') return generatedBlock + '\n';
  const separator = existingContent.endsWith('\n') ? '\n' : '\n\n';
  return existingContent + separator + generatedBlock + '\n';
}

// ─── File export ──────────────────────────────────────

/**
 * Export formatted lessons to a target file path.
 * Creates directories if needed. Uses sentinel-based injection for idempotent updates.
 */
export function exportLessons(lessons: ParsedLesson[], targetPath: string): void {
  const dir = path.dirname(targetPath);
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }

  const generatedBlock = formatLessonsAsMarkdown(lessons);

  if (fs.existsSync(targetPath)) {
    const existing = fs.readFileSync(targetPath, 'utf-8');
    const updated = injectSentinelBlock(existing, generatedBlock);
    fs.writeFileSync(targetPath, updated, 'utf-8');
  } else {
    fs.writeFileSync(targetPath, generatedBlock + '\n', 'utf-8');
  }
}
