# GENERATED by spikes/spine-adopt/src/lower.mts — do not hand-edit.
#
# Record:    r14-65ede9bf-dynamic-import-command-handlers.rule.yaml (specimen 65ede9bf-dynamic-import-command-handlers)
# Rule id:   65ede9bfdf6995fe
# Engine:    ast-grep
# Contract:  spikes/spine-adopt/rego/LOWERING.md
#
# § Lowering 8 — severity/message are compile-time constants, emitted for the
# report and deliberately NOT part of the verdict comparison.

package totem.spike.r65ede9bfdf6995fe

rule_id := "65ede9bfdf6995fe"

severity := "warning"

# ─── § Lowering 5 — scope: the § Design 7 two-array rule ───────────────────
#
# Globs were lowered to ANCHORED regexes on the TS side; the path is
# separator-normalised here exactly as `matchGlob` does (sys/glob.ts:354),
# and matching is case-SENSITIVE (no `i` anywhere in the shipped profile).

normalized_file := replace(input.file, "\\", "/")

positive_globs := [
	"^packages/cli/src/(?:[^/]+/)*[^/]*\\.ts$",
]

exclude_globs := [
	"^packages/cli/src/commands/(?:[^/]+/)*[^/]*\\.ts$",
	"^(?:[^/]+/)*[^/]*\\.test\\.ts$",
	"^(?:[^/]+/)*[^/]*\\.spec\\.ts$",
]

positive_match if {
	some g in positive_globs
	regex.match(g, normalized_file)
}

exclude_match if {
	some g in exclude_globs
	regex.match(g, normalized_file)
}

# An EMPTY positives list matches NOTHING (the record profile's direction,
# the opposite of legacy `fileMatchesGlobs`) — `positive_match` simply has
# no binding to succeed on.
in_scope if {
	positive_match
	not exclude_match
}

# ─── § Lowering 2 — strictness, made structural ────────────────────────────
#
# MEASURED, not assumed: an OPA WASM module has no `--strict-builtin-errors`
# equivalent. A `regex.match` compile failure inside a PARTIAL rule body
# simply yields no member, so an inexpressible pattern would degrade to an
# empty `violations` set — the fail-open § Lowering 2 calls
# spike-invalidating. Every emitted pattern is therefore exercised in the
# COMPLETE rule's body below: a compile failure makes `result` UNDEFINED, the
# entrypoint returns an empty result SET, and the host raises an error row.
# `is_boolean` is what keeps a legitimate non-match from failing the probe.
patterns_compile if {
	is_boolean(regex.match("^packages/cli/src/(?:[^/]+/)*[^/]*\\.ts$", ""))
	is_boolean(regex.match("^packages/cli/src/commands/(?:[^/]+/)*[^/]*\\.ts$", ""))
	is_boolean(regex.match("^(?:[^/]+/)*[^/]*\\.test\\.ts$", ""))
	is_boolean(regex.match("^(?:[^/]+/)*[^/]*\\.spec\\.ts$", ""))
}

# The FactBundle's own shape, asserted rather than assumed: a malformed bundle
# must be an error row too, never a silent zero-violation verdict.
facts_wellformed if {
	is_string(input.file)
	is_array(input.lines)
	is_array(input.astMatches)
	count([1 | some l in input.lines; is_string(l)]) == count(input.lines)
	count([1 | some m in input.astMatches; ast_match_wellformed(m)]) == count(input.astMatches)
}

ast_match_wellformed(m) if {
	is_number(m.lineNumber)
	is_string(m.lineText)
	is_string(m.startLineText)
}

# ─── § Lowering 7 — suppression ────────────────────────────────────────────

same_line_markers := [
	"totem-ignore",
	"totem-context:",
	"shield-context:",
]

preceding_line_markers := [
	"totem-ignore-next-line",
	"totem-context:",
]

# The ast arm carries the DUAL anchor: the reported line and its preceding
# line, PLUS the match's own `startLineText`/`startPrecedingLineText`.
suppressed(j) if {
	some m in same_line_markers
	contains(input.astMatches[j].lineText, m)
}

suppressed(j) if {
	some m in same_line_markers
	contains(input.astMatches[j].startLineText, m)
}

suppressed(j) if {
	ln := input.astMatches[j].lineNumber
	ln > 1
	some m in preceding_line_markers
	contains(input.lines[ln - 2], m)
}

suppressed(j) if {
	s := input.astMatches[j].startPrecedingLineText
	is_string(s)
	some m in preceding_line_markers
	contains(s, m)
}

# ─── § Lowering 1 — the output contract ────────────────────────────────────

# § Lowering 1: ast-grep ordinal is the MATCH INDEX — the shipped ast path
# emits one violation per MATCH (rule-engine.ts:1074), so two matches on one
# line are two violations and the ordinal is what keeps both in the set.
#
# Tree matching stays ENGINE-NATIVE: `input.astMatches` is received as FACTS
# (LOWERING.md § Ownership boundary). Rego owns everything downstream of the
# match — scope, suppression, requires, emission — and nothing upstream.
violations contains v if {
	in_scope
	some j, m in input.astMatches
	not suppressed(j)
	v := {"rule_id": rule_id, "line_number": m.lineNumber, "ordinal": j}
}

events contains e if {
	in_scope
	some j, m in input.astMatches
	not suppressed(j)
	e := {"kind": "trigger", "line_number": m.lineNumber, "ordinal": j}
}

# (N2) requires-first, then suppression — the shipped ast order
# (rule-engine.ts:1081 before :1109).
events contains e if {
	in_scope
	some j, m in input.astMatches
	suppressed(j)
	e := {"kind": "suppress", "line_number": m.lineNumber, "ordinal": j}
}

# The entrypoint. A COMPLETE rule guarded on the two structural probes, so
# any builtin error or malformed bundle leaves it UNDEFINED and the host sees
# an empty result SET — which it must raise as an error, never read as a
# zero-violation verdict (§ Lowering 2, and the Host contract's strictness).
result := {"violations": violations, "events": events} if {
	patterns_compile
	facts_wellformed
}
